### ISSUE TITLE
remove flares for Hummingbird

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Client-Mod#15]
Zero Flares for Hummingbird

**Comment by GNCLORD-MDB** [comment]
Erfolgt erster mit dem nächsten mod update, keine Zeit dafür jetzt mehr.

**Comment by Frozen-byte** [comment]
Kann das nicht in der Mission genutzt werden?

**Comment by Frozen-byte** [comment]
Aus Zeitgründen in Mission hotfixed, sollte noch im Mod gefixt werden
