### ISSUE TITLE
OPFOR Tigirs amunition defect

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Client-Mod#16]
Im am not able to open the Weapon configurator with Tigris at Arming-Pad near Beam-Pad

**Comment by GNCLORD-MDB** [comment]
Schießen geht mit mission version 121

**Comment by Frozen-byte** [comment]
Es geht um das bewaffnen. Das ist nicht auf dem Pad möglich. Und auf dem anderen (Nähe des Helikopter Pads) ist es nur ein einziges Mal nach Kauf möglich, danach nicht mehr.

**Comment by Frozen-byte** [comment]
Reopen: Die Fahrzeuge können nur aufschalten, wenn Radar an ist, bitte wieder Vanilla-Zustand herstellen.
