### ISSUE TITLE
Addon erstellt für Shop Dialoge

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Client-Mod#38]
Rohgerüst für neuen Shop erstellt

**Comment by Frozen-byte** [comment]
FEEDBACK SHOP TESTING:
> <19:26:48> "Mercurat": munitionskiste mit datalink ausrüstungbar
> <19:26:59> "Mercurat": hescos zu schmal bei ammopad
> <19:27:16> "Mercurat": kauf marschall, ausrüstet kaufen instadeath
> <19:28:42> "Mercurat": ich erwarte zu sehen was sich hinter dem dropdown menü verbirgt.das ist erst so wenn ich es öffne
> <19:30:34> "Mercurat": ich erwarte sehen zu könbnen wo ich mein fahrzeug hinstellen muss um es verkaufen zu könnemn
> <19:33:57> "Mercurat": das räumen ist im moment nur bei den pads möglich. ich würde gern alles räumen können was sich in der basis befindet
> <19:34:23> "Mercurat": es gibt vor dem räumen keine " bist du sicher " abfrage. das verhindert moneywaste
> <19:34:42> "Mercurat": das fahrezugbesetzen/nichtbesetzen resettet sich nach jedem kauf
> <19:35:02> "Mercurat": dem soll nicht so sein
> <19:35:30> "Mercurat": das vekaufsmenü schlie?t sich auch bei nichtbesetzen. dem sollte nicht so sein
> <19:37:27> "Mercurat": panzer kann man nicht abwählen zu besetzen
> <19:45:09> "Mercurat": Bei Verkauf Gutschriftanzeige mit Rot wo man Kauf und verkauf vergleicht und irgendwo -25% steht
> <19:39:06> "Raffda | Nils": erste auswahl  z.b fahrzeuge / Verkaufen ... flugzeuge / Verkaufen ist komisch verwirrend.
> <19:39:37> "Raffda | Nils": basis bewafnung ist da auch wenn man nix auswält
> <19:27:00> Schrecki<3*: qulin auswählen auf Fahrzeug besetzen klicken- nichts passiert
> <19:43:51> "Jörnrich": Habe zwei Taru Treibstoffvorrichtung bestellt. Der zweite ist mit dem ersten kollidiert und beide sind explodiert. Sollten wohl lieber weiter auseinander stehen ^^
> <19:49:01> "form": Kaufen: Fahrzeug "besetzten" Rechtschreibung, und irreführend als Button (besser Checkbox), und besser im Submenü platzieren
> <19:49:01> "form": Kaufen: Schnellboot HMG keine Bewaffnung auswählbar
> <19:49:01> "form": Verkaufen "ALLES Verkaufen" wäre sehr Hilfreich!
> <19:50:16> "Harbicht": Der Button zum Räumen des Ped ist zu leicht geklickt. Extra bestätigung und/oder andere Positionirung?

Daraus Extrahierte Checkliste:
- [ ] Datalink aktuell für alles ausrüstbar, sollte nur bei Sinnigem sein
- [ ] Kauffenster ist zu transparent
- [ ] Kollisionserkennung nicht funktionsfähig
- [ ] Preis und Konfigurationsanzeige nicht Deutlich genug (Position nicht auffällig?)
- [ ] Fahrzeugverkauf nicht intuitiv genug. ggf vom Shopsystem trennen, einfach nur ein Pad erstellen wo Fahrzeuge mit Motor aus automatisch verkauft werden?
- [ ] es gibt vor dem räumen keine " bist du sicher " abfrage. das verhindert moneywaste
- [ ] das Vekaufsmenü schließt sich auch bei "Fahrzeug nicht besetzen", ist unwahrscheinlich dass ich das Menü geschlossen haben will, wenn ich es nicht besetze

**Comment by GNCLORD-MDB** [comment]
Ok sehr gut, bitte die Addons mir zu Verfügung stellen , damit ich auf dem Dev server testen kann wenn ich was geändert habe.

**Comment by Frozen-byte** [comment]
DevServer bleibt erstmal so wie wir getestet haben, um die Reproduzierbarkeit zu gewähren. Kannst ihn dir jederzeit anmachen.

**Comment by GNCLORD-MDB** [comment]
Ich brauche noch die addons!

**Comment by Frozen-byte** [comment]
Arma3Sync Dev-Repo sollte dir eigentlich alle notwendigen Dateien liefern? 
AutoConfig ist gleich geblieben: `ftp://arma.opt4.net/opt-dev/.a3s/autoconfig`

**Comment by GNCLORD-MDB** [comment]
geschlossen, da bearbeitet
