### ISSUE TITLE
Hummingbird bekommt 30 Flares

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Client-Mod#49]
wie inhttps://opt4.net/calendar/event/4427-feintuning-green-hell/ beschlossen.

Akzeptanzkriterien:
Hummingbird soll auf beiden Seiten ~~24~~ 30 Flares bekommen.

**Comment by GNCLORD-MDB** [comment]
Wir haben ein 20 und ein 30 Magazin für die Flares.
Welches soll es dann sein ?

**Comment by Frozen-byte** [comment]
Dann bitte das 30er Magazin nehmen.
