### ISSUE TITLE
Datalink soll standartmäßig nicht ausgewählt sein

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Client-Mod#59]
Beim kauf von Fahrzeugen soll der Datalink explizit hinzugewählt werden, und nicht vorausgewählt sein.

**Comment by GNCLORD-MDB** [comment]
ok, wir geändert

**Comment by GNCLORD-MDB** [comment]
geschlossen, da bearbeitet
