### ISSUE TITLE
increase reloading time of AT-Launchers

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Client-Mod#6]
All handheld AT-Launchers should have a reloading time that roughly equals those of the Battle Tanks

**Comment by GNCLORD-MDB** [comment]
Wie es aussieht kann man nicht an Handwaffen die Nachladezeit ändern. 
Entsprechende Config Einträge haben keine Auswirkung.

**Comment by Frozen-byte** [comment]
Bist du dir sicher @GNCLORD-MDB vielleicht gibt es noch einen verstecken Eintrag?

Vielleicht kann sich das nochmal wer anders anschauen und eine Lösung finden.

**Comment by GNCLORD-MDB** [comment]
geschlossen, da bearbeitet
