### ISSUE TITLE
in den Zamak-Truppentransporter passen nur vier Leute.

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Client-Mod#67]
Es sollen 17 Leute rein passen.
(Bitte auch direkt den Tempest dazu checken)

Achtung es gibt covered und offenen, beide checken.

**Comment by GNCLORD-MDB** [comment]
Da wette ich das Leute den Logistik LKW gekauft haben. Der hat nur 4 Sitzplätze, da er ja fürs Transport von Dingen gedacht ist.

Der Truppen LKW kann 12-14 Leute mit nehmen.


ZAMAK TRANSPORT musste der Logistik LKW sein.

ZAMAK müßte der Truppen LKW sein.


Das gleiche ist so bei CSAT und NATO.

Das könnte ja jemand schnell testen

**Comment by GNCLORD-MDB** [comment]
Fertig umgesetzt

**Comment by Frozen-byte** [comment]
Wo ist der passende PR, der dieses Problem behandelt?
