### ISSUE TITLE
Ein paar Fehlermeldungen im Server-Log

### ISSUE THREAD

**Issue by formtapez** [OperationPandoraTrigger/OPT-Client-Mod#90]
@GNCLORD-MDB der ClientMod ist noch etwas "gesprächig":

Error: Weapon[OPT_CUP_srifle_AS50]: max attachments slots count reached(maximum = 5)!  Attachment slot[CUP_PicatinnyTopMountAK] for weapon's proxy[default]

10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_arifle_HK416_Black/WeaponSlotsInfo/
10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_arifle_Mk16_STD_FG_black/WeaponSlotsInfo/
10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_arifle_Mk16_STD_EGLM_black/WeaponSlotsInfo/
10:42:00 Cannot find base CUP_PicatinnyTopShortMount for opt\opt_client\addons\weapons\config.bin/CfgWeapons/OPT_CUP_arifle_Mk16_STD_EGLM_black/WeaponSlotsInfo/CUP_PicatinnyTopMountSCAR/
10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_arifle_AK101_railed/WeaponSlotsInfo/
10:42:00 Cannot find base CUP_PicatinnyTopShortMount for opt\opt_client\addons\weapons\config.bin/CfgWeapons/OPT_CUP_arifle_AK101_railed/WeaponSlotsInfo/CUP_PicatinnyTopMountAK/
10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_arifle_AK101_GL_railed/WeaponSlotsInfo/
10:42:00 Cannot find base CUP_PicatinnyTopShortMount for opt\opt_client\addons\weapons\config.bin/CfgWeapons/OPT_CUP_arifle_AK101_GL_railed/WeaponSlotsInfo/CUP_PicatinnyTopMountAK/
10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_lmg_m249_pip3/WeaponSlotsInfo/
10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_lmg_M240_B/WeaponSlotsInfo/
10:42:00 Cannot find base CUP_PicatinnyTopShortMount for opt\opt_client\addons\weapons\config.bin/CfgWeapons/OPT_CUP_lmg_M240_B/WeaponSlotsInfo/CUP_PicatinnyTopMountM240/
10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_arifle_RPK74M_top_rail/WeaponSlotsInfo/
10:42:00 Cannot find base CUP_PicatinnyTopShortMount for opt\opt_client\addons\weapons\config.bin/CfgWeapons/OPT_CUP_arifle_RPK74M_top_rail/WeaponSlotsInfo/CUP_PicatinnyTopMountAK/
10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_lmg_PKM_top_rail/WeaponSlotsInfo/
10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_arifle_HK417_20/WeaponSlotsInfo/
10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_arifle_FNFAL5061_railed/WeaponSlotsInfo/
10:42:00 Cannot find base CUP_PicatinnyTopShortMount for opt\opt_client\addons\weapons\config.bin/CfgWeapons/OPT_CUP_srifle_AS50/WeaponSlotsInfo/CUP_PicatinnyTopMountAS50/
10:42:00 Cannot find base WeaponSlotsInfo for opt\opt_client\addons\weapons\config.bin/CfgWeapons/CUP_smg_Mac10/WeaponSlotsInfo/

10:42:28 String STR_A3_C_CfgVehicles_B_HMG_02_high_weapon_F0 not found
10:42:28 String STR_A3_C_CfgVehicles_O_HMG_02_high_weapon_F0 not found

**Comment by GNCLORD-MDB** [comment]
jo schau mir mal an wieso das da fehlt

**Comment by GNCLORD-MDB** [comment]
gefixt
